@startuml diagrama de balatro

title diagrama de clases

abstract carta{
    - valor:Int
    - multiplicador:Int 
    ---
    + compararCon(carta:Carta):bool
    + compararValor(carta:Carta):bool
    + calcularPuntaje():Puntaje
    + aplicarTarot(tarot:Tarot)
}

class Puntaje{
    - multiplicador: Int
    ---
    +{static} Puntaje(multiplicador:int):Puntaje
    +comparar
}


abstract Tarot implements Modificable{
    + m0odificar(unValor:int):Int
}

class tarotDeValor extends Tarot{
    + modificar(unValor:int):Int
}

class tarotDeMultiplicador extends Tarot{
    + modificar(unValor:int):Int
}

interface Modificable{
    + modificar(unValor:int):Int
}

class jugador{
    - puntosTotales:Puntaje
    
}

@enduml